package com.petsay.database.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.petsay.vo.chat.ChatContacts;
import com.petsay.vo.chat.ChatMsgEntity;
import com.petsay.vo.chat.NewestMsg;
import com.petsay.vo.chat.ChatBlack;
import com.petsay.vo.petalk.PetTagVo;
import com.petsay.vo.petalk.DecorationPosition;
import com.petsay.vo.petalk.DraftboxVo;

import com.petsay.database.greendao.chat.ChatContactsDao;
import com.petsay.database.greendao.chat.ChatMsgEntityDao;
import com.petsay.database.greendao.chat.NewestMsgDao;
import com.petsay.database.greendao.chat.ChatBlackDao;
import com.petsay.database.greendao.petsay.PetTagVoDao;
import com.petsay.database.greendao.petsay.DecorationPositionDao;
import com.petsay.database.greendao.petsay.DraftboxVoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatContactsDaoConfig;
    private final DaoConfig chatMsgEntityDaoConfig;
    private final DaoConfig newestMsgDaoConfig;
    private final DaoConfig chatBlackDaoConfig;
    private final DaoConfig petTagVoDaoConfig;
    private final DaoConfig decorationPositionDaoConfig;
    private final DaoConfig draftboxVoDaoConfig;

    private final ChatContactsDao chatContactsDao;
    private final ChatMsgEntityDao chatMsgEntityDao;
    private final NewestMsgDao newestMsgDao;
    private final ChatBlackDao chatBlackDao;
    private final PetTagVoDao petTagVoDao;
    private final DecorationPositionDao decorationPositionDao;
    private final DraftboxVoDao draftboxVoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatContactsDaoConfig = daoConfigMap.get(ChatContactsDao.class).clone();
        chatContactsDaoConfig.initIdentityScope(type);

        chatMsgEntityDaoConfig = daoConfigMap.get(ChatMsgEntityDao.class).clone();
        chatMsgEntityDaoConfig.initIdentityScope(type);

        newestMsgDaoConfig = daoConfigMap.get(NewestMsgDao.class).clone();
        newestMsgDaoConfig.initIdentityScope(type);

        chatBlackDaoConfig = daoConfigMap.get(ChatBlackDao.class).clone();
        chatBlackDaoConfig.initIdentityScope(type);

        petTagVoDaoConfig = daoConfigMap.get(PetTagVoDao.class).clone();
        petTagVoDaoConfig.initIdentityScope(type);

        decorationPositionDaoConfig = daoConfigMap.get(DecorationPositionDao.class).clone();
        decorationPositionDaoConfig.initIdentityScope(type);

        draftboxVoDaoConfig = daoConfigMap.get(DraftboxVoDao.class).clone();
        draftboxVoDaoConfig.initIdentityScope(type);

        chatContactsDao = new ChatContactsDao(chatContactsDaoConfig, this);
        chatMsgEntityDao = new ChatMsgEntityDao(chatMsgEntityDaoConfig, this);
        newestMsgDao = new NewestMsgDao(newestMsgDaoConfig, this);
        chatBlackDao = new ChatBlackDao(chatBlackDaoConfig, this);
        petTagVoDao = new PetTagVoDao(petTagVoDaoConfig, this);
        decorationPositionDao = new DecorationPositionDao(decorationPositionDaoConfig, this);
        draftboxVoDao = new DraftboxVoDao(draftboxVoDaoConfig, this);

        registerDao(ChatContacts.class, chatContactsDao);
        registerDao(ChatMsgEntity.class, chatMsgEntityDao);
        registerDao(NewestMsg.class, newestMsgDao);
        registerDao(ChatBlack.class, chatBlackDao);
        registerDao(PetTagVo.class, petTagVoDao);
        registerDao(DecorationPosition.class, decorationPositionDao);
        registerDao(DraftboxVo.class, draftboxVoDao);
    }
    
    public void clear() {
        chatContactsDaoConfig.getIdentityScope().clear();
        chatMsgEntityDaoConfig.getIdentityScope().clear();
        newestMsgDaoConfig.getIdentityScope().clear();
        chatBlackDaoConfig.getIdentityScope().clear();
        petTagVoDaoConfig.getIdentityScope().clear();
        decorationPositionDaoConfig.getIdentityScope().clear();
        draftboxVoDaoConfig.getIdentityScope().clear();
    }

    public ChatContactsDao getChatContactsDao() {
        return chatContactsDao;
    }

    public ChatMsgEntityDao getChatMsgEntityDao() {
        return chatMsgEntityDao;
    }

    public NewestMsgDao getNewestMsgDao() {
        return newestMsgDao;
    }

    public ChatBlackDao getChatBlackDao() {
        return chatBlackDao;
    }

    public PetTagVoDao getPetTagVoDao() {
        return petTagVoDao;
    }

    public DecorationPositionDao getDecorationPositionDao() {
        return decorationPositionDao;
    }

    public DraftboxVoDao getDraftboxVoDao() {
        return draftboxVoDao;
    }

}
