package com.petsay.vo.petalk;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table PET_TAG_VO.
 */
public class PetTagVo implements Serializable {

    private static final long serialVersionUID = 6742651415669016890L;

    private String id;
    private String name;
    private String iconUrl;
    private String bgUrl;
    private String detailUrl;
    private String ctrl;
    private Boolean deleted;
    private String createTime;

    public PetTagVo() {
    }

    public PetTagVo(String id, String name, String iconUrl, String bgUrl, String detailUrl, String ctrl, Boolean deleted, String createTime) {
        this.id = id;
        this.name = name;
        this.iconUrl = iconUrl;
        this.bgUrl = bgUrl;
        this.detailUrl = detailUrl;
        this.ctrl = ctrl;
        this.deleted = deleted;
        this.createTime = createTime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getBgUrl() {
        return bgUrl;
    }

    public void setBgUrl(String bgUrl) {
        this.bgUrl = bgUrl;
    }

    public String getDetailUrl() {
        return detailUrl;
    }

    public void setDetailUrl(String detailUrl) {
        this.detailUrl = detailUrl;
    }

    public String getCtrl() {
        return ctrl;
    }

    public void setCtrl(String ctrl) {
        this.ctrl = ctrl;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

}
