package com.petsay.vo.chat;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_BLACK.
 */
public class ChatBlack {

    private Long id;
    private String petId;

    public ChatBlack() {
    }

    public ChatBlack(Long id) {
        this.id = id;
    }

    public ChatBlack(Long id, String petId) {
        this.id = id;
        this.petId = petId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPetId() {
        return petId;
    }

    public void setPetId(String petId) {
        this.petId = petId;
    }

}
